const actionType = {
    LOAD_DATA_PROGRESS: 'LOAD_DATA_PROGRESS',
    LOAD_DATA_SUCCEED: 'LOAD_DATA_SUCCEED',
    LOAD_DATA_FAIL: 'LOAD_DATA_FAIL',

    SET_CURRENTUSER_PROGRESS: 'SET_CURRENTUSER_PROGRESS',
    SET_CURRENTUSER_SUCCEED: 'SET_CURRENTUSER_SUCCEED',
    SET_CURRENTUSER_FAIL: 'SET_CURRENTUSER_FAIL',

    SET_DATAOBJ_PROGRESS: 'SET_DATAOBJ_PROGRESS',
    SET_DATAOBJ_SUCCEED: 'SET_DATAOBJ_SUCCEED',
    SET_DATAOBJ_FAIL: 'SET_DATAOBJ_FAIL',

    SET_INVENTORY_PROGRESS: 'SET_INVENTORY_PROGRESS',
    SET_INVENTORY_SUCCEED: 'SET_INVENTORY_SUCCEED',
    SET_INVENTORY_FAIL: 'SET_INVENTORY_FAIL',

    PUSH_HISTORY_PROGRESS: 'PUSH_HISTORY_PROGRESS',
    PUSH_HISTORY_SUCCEED: 'PUSH_HISTORY_SUCCEED',
    PUSH_HISTORY_FAIL: 'PUSH_HISTORY_FAIL',


    SYNC_DATA_PROGRESS: 'SYNC_DATA_PROGRESS',
    SYNC_DATA_SUCCEED: 'SYNC_DATA_SUCCEED',
    SYNC_DATA_FAIL: 'SYNC_DATA_FAIL',

    DELETE_LOCKER_PROGRESS: 'DELETE_LOCKER_PROGRESS',
    DELETE_LOCKER_SUCCEED: 'DELETE_LOCKER_SUCCEED',
    DELETE_LOCKER_FAIL: 'DELETE_LOCKER_FAIL',


    SET_LOCALDB_FLAG: 'SET_LOCALDB_FLAG',


    LOAD_LOCALDATADB_PROGRESS: 'LOAD_LOCALDATADB_PROGRESS',
    LOAD_LOCALDATADB_SUCCEED: 'LOAD_LOCALDATADB_SUCCEED',
    LOAD_LOCALDATADB_INVENTORY_SUCCEED: 'LOAD_LOCALDATADB_INVENTORY_SUCCEED',
    LOAD_LOCALDATADB_FAIL: 'LOAD_LOCALDATADB_FAIL',

    ADD_USER_PROGRESS: 'ADD_USER_PROGRESS',
    ADD_USER_SUCCEED: 'ADD_USER_SUCCEED',
    ADD_USER_FAIL: 'ADD_USER_FAIL',

    DELETE_USER_PROGRESS: 'DELETE_USER_PROGRESS',
    DELETE_USER_SUCCEED: 'DELETE_USER_SUCCEED',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',


    ADD_LOCKER_PROGRESS: 'ADD_LOCKER_PROGRESS',
    ADD_LOCKER_SUCCEED: 'ADD_LOCKER_SUCCEED',
    ADD_LOCKER_FAIL: 'ADD_LOCKER_FAIL',


    DELETE_LOCAL_LOCKER_PROGRESS: 'DELETE_LOCAL_LOCKER_PROGRESS',
    DELETE_LOCAL_LOCKER_SUCCEED: 'DELETE_LOCAL_LOCKER_SUCCEED',
    DELETE_LOCAL_LOCKER_FAIL: 'DELETE_LOCAL_LOCKER_FAIL',


    ADD_INVENTORY_PROGRESS: 'ADD_INVENTORY_PROGRESS',
    ADD_INVENTORY_SUCCEED: 'ADD_INVENTORY_SUCCEED',
    ADD_INVENTORY_FAIL: 'ADD_INVENTORY_FAIL',


    DELETE_INVENTORY_PROGRESS: 'DELETE_INVENTORY_PROGRESS',
    DELETE_INVENTORY_SUCCEED: 'DELETE_INVENTORY_SUCCEED',
    DELETE_INVENTORY_FAIL: 'DELETE_INVENTORY_FAIL',


    UPDATE_INVENTORY_PROGRESS: 'UPDATE_INVENTORY_PROGRESS',
    UPDATE_INVENTORY_SUCCEED: 'UPDATE_INVENTORY_SUCCEED',
    UPDATE_INVENTORY_FAIL: 'UPDATE_INVENTORY_FAIL',


    UPDATE_USER_PROGRESS: 'UPDATE_USER_PROGRESS',
    UPDATE_USER_SUCCEED: 'UPDATE_USER_SUCCEED',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',


    UPDATE_LOCKER_PROGRESS: 'UPDATE_LOCKER_PROGRESS',
    UPDATE_LOCKER_SUCCEED: 'UPDATE_LOCKER_SUCCEED',
    UPDATE_LOCKER_FAIL: 'UPDATE_LOCKER_FAIL',


    ADD_HISTORY_USER_PROGRESS: 'ADD_HISTORY_USER_PROGRESS',
    ADD_HISTORY_USER_SUCCEED: 'ADD_HISTORY_USER_SUCCEED',
    ADD_HISTORY_USER_FAIL: 'ADD_HISTORY_USER_FAIL',


    ADD_HISTORY_LOCKER_PROGRESS: 'ADD_HISTORY_LOCKER_PROGRESS',
    ADD_HISTORY_LOCKER_SUCCEED: 'ADD_HISTORY_LOCKER_SUCCEED',
    ADD_HISTORY_LOCKER_FAIL: 'ADD_HISTORY_LOCKER_FAIL'




}

export default actionType;